const koa=require('koa')
const bodyParser=require('koa-bodyparser')
const userRouter=require('./app/api/user')
const tokenRouter=require('./app/api/token')
const app=new koa()
app.use(bodyParser())
app.use(userRouter.routes())
app.use(tokenRouter.routes())
app.listen(3000)
